export const START_MOVIES_LOADING = 'START_MOVIES_LOADING';
export const STOP_MOVIES_LOADING = 'STOP_MOVIES_LOADING';
export const SET_MOVIES = 'SET_MOVIES';
export const SET_CURRENT_MOVIE = 'SET_CURRENT_MOVIE';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_ALL_GENRE = 'SET_ALL_GENRE';